language: java
jdk: oraclejdk7
sudo: false
addons:
  apt:
    packages:
      - mesa-utils
install: mvn -f sci-vis-framework install -DskipTests=true
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: mvn -f sci-vis-framework test
