language: java
jdk: oraclejdk7
sudo: false
install: mvn -f sci-vis-framework install -DskipTests=true
script: mvn -f sci-vis-framework test
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
